src/locale/en/translation.json, src/locale/nl/translation.json, src/pages/settings/plugins.html, src/resources/blockly/blockly.js, src/wizards/basewizard.html, tests/translations.py
Fixes #27
Fixes #26
Fixes #24
Fixes #23
=> Various small tweaks.

index.html, src/index.html, src/locale/en/translation.json, src/locale/nl/translation.json, src/pages/outputs.html, src/pages/settings/plugins.html, src/pages/thermostats.html, src/pages/thermostats.js, src/resources/schedule/schedule.js, src/resources/slider/slider.js, src/styles/openmotics.css, src/users.html
=> Various small fixes and tweaks

src/containers/input.js, src/pages/settings/outputs.html, src/resources/valueconverters.js, src/usermanagement/create.html, src/usermanagement/create.js
Display timer as "Disabled" when it's set to 0 seconds
Hide internal system user
=> Display Input names, even if they are inactive

src/components/api.js, src/pages/settings/initialisation.html, src/pages/settings/initialisation.js
=> Add Energy Module to "discover" button

src/components/authentication.js, src/components/shared.js, src/containers/plugin.js, src/index.html, src/index.js, src/locale/en/translation.json, src/locale/nl/translation.json, src/pages/navigation.html, src/pages/plugins/index.html, src/pages/plugins/index.js, src/pages/settings/plugins.html, src/resources/valueconverters.js, src/wizards/basewizard.js
=> Webui support

package.json, src/usermanagement/create.js
=> Make sure usernames don't end with whitespaces

package.json, src/containers/input.js, src/containers/led.js, src/locales/en/translation.json, src/locales/nl/translation.json, src/pages/settings/inputs.html, src/pages/settings/inputs.js, src/wizards/configureinput/configure.html, src/wizards/configureinput/configure.js, src/wizards/configureinput/data.js, src/wizards/configureinput/feedback.js, src/wizards/configureinput/general.js, src/wizards/configureinput/index.js, webpack.config.js
… + Resolve a "Generic feedback" issue
=> Make it easier to let an Input just execute a Group Action

src/components/api-base.js, src/locales/en/translation.json, src/locales/nl/translation.json, src/pages/settings/initialisation.js, src/pages/settings/thermostats.html, src/wizards/configureglobalthermostat/general.js, src/wizards/configureglobalthermostat/switching.html, src/wizards/configureglobalthermostat/switching.js
Caching race condition + Handle no outside sensor better + Some translations + Detection of CAN Control
=> Fixes a few small issues

index.ejs, package.json, src/components/api-cloud.js, src/containers/role.js, src/containers/schedule.js, src/index.html, src/index.js, src/locales/en/translation.json, src/locales/nl/translation.json, src/pages/cloud/installations.js, src/pages/settings/apps.html, src/pages/settings/apps.js, src/pages/settings/users.html, src/pages/settings/users.js, src/resources/blockly/blockly.html, src/usermanagement/login.html, src/users.html, src/wizards/configureinput/configure.js, src/wizards/configureschedule/schedule.js, src/wizards/configureuser/credentials.js, src/wizards/configureuser/data.js, src/wizards/configureuser/general.html, src/wizards/configureuser/general.js, src/wizards/configureuser/index.js, webpack.config.js
* Adapt to API changes (new API in development/testing)
* Hide schedule "next execution" if it's not yet available (iso showing 1970)
* Don't report App installation as failed if it was successful
* Show email or username in login window (depending on build target)
* Don't complain about not selected GroupAction (fixes #159)
* Show/hide feature specific navigation items correctly
* Show frontend version in splash screen
=> Various (small) bugfixes

tests/integration/helper.py, tests/integration/tests/test_create_login.py
[OM-340]
[OM-340]: https://openmotics.atlassian.net/browse/OM-340
=> testee enters authorized mode only if it didn't already

package-lock.json, src/main.js
=> Loading times

package.json, src/resources/blockly/blockly-blocks.js, src/resources/blockly/blockly-env.js
* Shutter groups were not correctly shown
* Day condition wasn't selectable
=> Solves two small issues in the blockly interface

src/index.js
=> PO-136: Fixed first updates check

package.json, src/locales/en/translation.json, src/locales/nl/translation.json, src/pages/setup/inputs/configure-input/general.html, src/pages/setup/inputs/configure-input/general.js, src/pages/setup/inputs/configure-input/styles.css, src/pages/setup/inputs/index.js
@khenderick I think to test it we need to check the save issue.
=> PO-157: Fixed not in use filter for inputs

src/components/api-cloud.js, src/pages/dashboard/index.js, src/pages/outputs/index.js, src/pages/setup/cloud/floors-rooms/index.js
- We now request the MEDIUM size image
- On the output page, I filter out floors without an image
=> PO-168: Floor plan changes

src/containers/installation.js, src/locales/en/translation.json, src/locales/nl/translation.json, src/pages/cloud/installations.html
https://openmotics.atlassian.net/browse/PO-182
=> PO-182: Added internal name field

src/containers/app.js, src/locales/en/translation.json, src/locales/nl/translation.json, src/pages/settings/apps/index.html, src/pages/settings/apps/index.js, src/pages/settings/apps/styles.css
=> PO-166: Added feature to update the plugins

package-lock.json, package.json, src/index.js, src/locales/en/translation.json, src/locales/nl/translation.json, src/pages/cloud/installations.html, src/pages/cloud/installations.js, src/pages/cloud/thermostats/index.html, src/pages/cloud/thermostats/index.js, src/pages/dashboard/index.html, src/pages/dashboard/index.js, src/pages/settings/energy/index.js, src/pages/settings/maintenance/index.html, src/pages/setup/environment/index.js, src/pages/setup/inputs/configure-input/configure.js, src/pages/setup/inputs/configure-input/general.js, src/pages/setup/inputs/index.html, src/pages/setup/outputs/configure-output/index.js, src/pages/setup/outputs/configure-shutter/index.js, src/pages/setup/thermostats/index.html, src/pages/setup/thermostats/index.js, src/resources/base.js, src/resources/thermostatgroup/thermostat.html, src/wizards/configureinput/general.js
* Fxied validation of input
* Renamed sync button
* Translations fixed
* Tests fixed
* Fixed room dropdown issue
* Bump http-proxy from 1.17.0 to 1.18.1 (#368)
Bumps [http-proxy](https://github.com/http-party/node-http-proxy) from 1.17.0 to 1.18.1.
- [Release notes](https://github.com/http-party/node-http-proxy/releases)
- [Changelog](https://github.com/http-party/node-http-proxy/blob/master/CHANGELOG.md)
- [Commits](https://github.com/http-party/node-http-proxy/compare/1.17.0...1.18.1)
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
* Bump tree-kill from 1.2.0 to 1.2.2 (#367)
Bumps [tree-kill](https://github.com/pkrumins/node-tree-kill) from 1.2.0 to 1.2.2.
- [Release …
=> master → develop

src/pages/settings/cloud/updates/index.html, src/pages/settings/cloud/updates/index.js
=> PO-252: Added alert

docker/Dockerfile, docker/entrypoint.sh, docker/portal.conf
Redirect */qr(/)?(.*) to *
=> handle QR-code requests to main page for now
=> Qr redirect

src/components/api-cloud.js, src/locales/en/translation.json, src/locales/nl/translation.json, src/pages/settings/schedules/index.html, src/pages/settings/schedules/index.js, src/pages/setup/environment/index.js
=> Fixed group action

src/pages/setup/outputs/index.js
Shutter locking is not implemented on the gateway.
=> use v0 apis on setup outputs page where possible

src/pages/setup/thermostats/index.js
remove all cloud api usages from the thermostats page
=> multi-gateway thermostat setup

src/pages/gateway/thermostats.js, src/pages/setup/inputs/index.js, src/pages/setup/outputs/index.js
With multi-gateway installations changes originating from all gateways
are broadcast to the installation group.
=> filter websocket events for the selected gateway

src/containers/eventrule.js, src/pages/settings/cloud/eventrules/index.html, src/pages/settings/cloud/eventrules/index.js, src/wizards/configureeventrule/configure.js
This is a cloud only page so outputs here should also use v1.1
=> FE-728 fix output selection for eventrules
